### ISSUE TITLE
IndexOutOfRangeException in Reminiscence on Router methods

### ISSUE THREAD

**Issue by nyz93** [OsmSharp/routing#4]
I tried first with `Router.Calculate`, then I got an exception, then tried to resolve every point with `Router.TryResolve`, but that throws the same one as well.
The datasource I'm working with is loaded from an overpass response, through XmlOsmStreamSource, and I've tried running `RouterDb.AddContracted` on the data, it should be correct.

The exception:
```
System.IndexOutOfRangeException was unhandled by user code
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=Reminiscence
  StackTrace:
       at Reminiscence.Arrays.MemoryArray`1.get_Item(Int64 idx)
       at OsmSharp.Routing.Graphs.Geometric.Shapes.Shape.get_Item(Int32 i)
       at OsmSharp.Routing.Graphs.Geometric.Shapes.ShapeBase.ShapeBaseEnumerator.get_Current()
       at OsmSharp.Routing.Algorithms.Search.Hilbert.SearchClosestEdge(GeometricGraph graph, Single latitude, Single longitude, Single latitudeOffset, Single longitudeOffset, Single maxDistanceMeter, Func`2 isOk)
       at OsmSharp.Routing.Algorithms.Search.ResolveAlgorithm.DoRun()
       at OsmSharp.Routing.Algorithms.AlgorithmBase.Run()
       at OsmSharp.Routing.Router.TryResolve(Profile[] profiles, Single latitude, Single longitude, Func`2 isBetter, Single maxSearchDistance)
       at OsmSharp.Routing.IRouterExtensions.TryResolve(IRouter router, Profile[] profiles, ICoordinate coordinate, Single searchDistanceInMeter)
       at OsmSharp.Routing.IRouterExtensions.TryResolve(IRouter router, Profile profile, ICoordinate coordinate, Single searchDistanceInMeter)
       [...client code...]
  InnerException: 
```

My OS is Windows 7 64-bit, OsmSharp.Routing is downloaded from NuGet with -IncludePrerelease.

**Comment by xivk** [comment]
TryResolve is not thread-safe. Are you by any chance accessing the router from multiple threads?

**Comment by nyz93** [comment]
Indeed I was, now that I call it from the same thread I've created the Router object it works. Thank you.
